[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "n_queens_solver"
version = "0.1"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pygame"
]